name: Crasher
main: me.crafter.mc.crasher.Crasher
version: 1.1
author: Frank

permissions:
   crasher.use:
      default: op

commands:
   crash:
      permission: crasher.use
      description: Crash someone.
      usage: |
         /crash
